In [1]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1781314679.970794  106732 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1781314679.971339  106732 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1781314680.032591  106732 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1781314681.371534  106732 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1781314681.372176  106732 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
df = pd.read_csv("insurance.csv")

In [3]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [5]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [6]:
df.children.unique()

array([0, 1, 3, 2, 5, 4])

In [7]:
df.sex.unique()

array(['female', 'male'], dtype=object)

In [8]:
df.smoker.unique()

array(['yes', 'no'], dtype=object)

In [9]:
df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [10]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(1)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [18]:
X = df.drop("charges",axis=1)

In [19]:
y = df.charges

In [20]:
num_cols = X.select_dtypes(include=[int,float]).columns.tolist()

In [21]:
cat_cols = X.select_dtypes(include=object).columns.tolist()

In [22]:
num_cols

['age', 'bmi', 'children']

In [23]:
cat_cols

['sex', 'smoker', 'region']

In [24]:
num_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

In [25]:
cat_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(drop='first', sparse_output=False))
])

In [26]:
preprocessor = ColumnTransformer([
    ('num', num_transformer, num_cols),
    ('cat', cat_transformer, cat_cols)
])

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [28]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [29]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')  # <-- KEY DIFFERENCE
])

/home/funter-pie/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1781315431.630337  106732 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [30]:
model.compile(optimizer='adam', loss='mse')

In [31]:
history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 305551136.0000 - val_loss: 316745984.0000
Epoch 2/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 305476576.0000 - val_loss: 316631456.0000
Epoch 3/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 305294656.0000 - val_loss: 316370464.0000
Epoch 4/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 304900864.0000 - val_loss: 315832096.0000
Epoch 5/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 304157440.0000 - val_loss: 314884224.0000
Epoch 6/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 302923040.0000 - val_loss: 313392160.0000
Epoch 7/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 301075968.0000 - val_loss: 311222144.0000
Epoch 8/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 298482080.0000 - val_loss: 308325376.0000
Epoch 9/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 294984928.0000 - val_loss: 304545056.0000
Epoch 10/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 290735712.0000 - val_loss: 299813280.0000
Epoch 11/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 285585440.0000 - val_loss: 294239488.0000
Epoch 12/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 279092512.0000 - val_loss: 287337792.0000
Epoch 13/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 271649792.0000 - val_loss: 279338368.0000
Epoch 14/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 262778048.0000 - val_loss: 270308384.0000
Epoch 15/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 253600592.0000 - val_loss: 260350448.0000
Epoch 16/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 242370064.0000 - val_loss: 249498128.0000
Epoch 17/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 230914320.0000 - val_loss: 237931200.0000
Epoch 18/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 218987248.0000 - val_loss: 225559392.0000
Epoch 19/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 206663584.0000 - val_loss: 213192144.0000
Epoch 20/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 194875440.0000 - val_loss: 200614304.0000
Epoch 21/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 180985136.0000 - val_loss: 187997744.0000
Epoch 22/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 169057248.0000 - val_loss: 176276144.0000
Epoch 23/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 158393712.0000 - val_loss: 164695936.0000
Epoch 24/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 147554080.0000 - val_loss: 153690816.0000
Epoch 25/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 137180512.0000 - val_loss: 144381392.0000
Epoch 26/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 128598808.0000 - val_loss: 136171216.0000
Epoch 27/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 121707592.0000 - val_loss: 128319032.0000
Epoch 28/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 116741056.0000 - val_loss: 122310304.0000
Epoch 29/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 111570784.0000 - val_loss: 117421480.0000
Epoch 30/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 106818056.0000 - val_loss: 113023528.0000
Epoch 31/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 103026960.0000 - val_loss: 109265808.0000
Epoch 32/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 99237104.0000 - val_loss: 106255176.0000
Epoch 33/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 96985384.0000 - val_loss: 103556008.0000
Epoch 34/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 95708936.0000 - val_loss: 101754968.0000
Epoch 35/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 94837144.0000 - val_loss: 99928144.0000
Epoch 36/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 93113128.0000 - val_loss: 98448648.0000
Epoch 37/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 93047040.0000 - val_loss: 96962016.0000
Epoch 38/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 91551200.0000 - val_loss: 95621624.0000
Epoch 39/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 92140072.0000 - val_loss: 94664552.0000
Epoch 40/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 91082800.0000 - val_loss: 93714736.0000
Epoch 41/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 88391984.0000 - val_loss: 92562096.0000
Epoch 42/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 87025936.0000 - val_loss: 91644240.0000
Epoch 43/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 87854568.0000 - val_loss: 90735928.0000
Epoch 44/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 87444024.0000 - val_loss: 89739184.0000
Epoch 45/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 83909424.0000 - val_loss: 88839696.0000
Epoch 46/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 86162416.0000 - val_loss: 87902680.0000
Epoch 47/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 83470032.0000 - val_loss: 87056488.0000
Epoch 48/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 84079984.0000 - val_loss: 86281528.0000
Epoch 49/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 84356560.0000 - val_loss: 85516888.0000
Epoch 50/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 81611432.0000 - val_loss: 84653824.0000
Epoch 51/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 82358456.0000 - val_loss: 83738008.0000
Epoch 52/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 80622672.0000 - val_loss: 82904352.0000
Epoch 53/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 79069368.0000 - val_loss: 82009800.0000
Epoch 54/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 77980720.0000 - val_loss: 80943368.0000
Epoch 55/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 77080472.0000 - val_loss: 79835480.0000
Epoch 56/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 75441928.0000 - val_loss: 79174632.0000
Epoch 57/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 76799192.0000 - val_loss: 78504480.0000
Epoch 58/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 75183368.0000 - val_loss: 77693312.0000
Epoch 59/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 75011776.0000 - val_loss: 76697072.0000
Epoch 60/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 72550168.0000 - val_loss: 75931496.0000
Epoch 61/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 73082696.0000 - val_loss: 75185256.0000
Epoch 62/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 72622616.0000 - val_loss: 74417360.0000
Epoch 63/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 73195424.0000 - val_loss: 73726184.0000
Epoch 64/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 69938392.0000 - val_loss: 72816840.0000
Epoch 65/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 69427896.0000 - val_loss: 72185240.0000
Epoch 66/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 70562368.0000 - val_loss: 71434248.0000
Epoch 67/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 69100016.0000 - val_loss: 70394672.0000
Epoch 68/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 68418032.0000 - val_loss: 69682368.0000
Epoch 69/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 68401424.0000 - val_loss: 68972752.0000
Epoch 70/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 64757804.0000 - val_loss: 68181320.0000
Epoch 71/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 65333356.0000 - val_loss: 67406112.0000
Epoch 72/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 64879456.0000 - val_loss: 66177828.0000
Epoch 73/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 64403272.0000 - val_loss: 65435420.0000
Epoch 74/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 62027008.0000 - val_loss: 64717600.0000
Epoch 75/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 61822364.0000 - val_loss: 64145456.0000
Epoch 76/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 61562268.0000 - val_loss: 63507256.0000
Epoch 77/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 60794624.0000 - val_loss: 62916224.0000
Epoch 78/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 59177132.0000 - val_loss: 62034608.0000
Epoch 79/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 60699012.0000 - val_loss: 61397088.0000
Epoch 80/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 58232176.0000 - val_loss: 60861296.0000
Epoch 81/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 58399272.0000 - val_loss: 60284212.0000
Epoch 82/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 59561140.0000 - val_loss: 59470116.0000
Epoch 83/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 56415288.0000 - val_loss: 58909760.0000
Epoch 84/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 57477600.0000 - val_loss: 58189656.0000
Epoch 85/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 55527680.0000 - val_loss: 57632144.0000
Epoch 86/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 54749676.0000 - val_loss: 56887912.0000
Epoch 87/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 55681416.0000 - val_loss: 56212080.0000
Epoch 88/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 53652908.0000 - val_loss: 55637648.0000
Epoch 89/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 54055312.0000 - val_loss: 55094104.0000
Epoch 90/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 53972548.0000 - val_loss: 54403920.0000
Epoch 91/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 52882136.0000 - val_loss: 53745152.0000
Epoch 92/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 52273856.0000 - val_loss: 53092660.0000
Epoch 93/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 53195988.0000 - val_loss: 52566728.0000
Epoch 94/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 51385532.0000 - val_loss: 52106900.0000
Epoch 95/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 49261560.0000 - val_loss: 51663488.0000
Epoch 96/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 49221944.0000 - val_loss: 51133008.0000
Epoch 97/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 48377484.0000 - val_loss: 50515844.0000
Epoch 98/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 48576080.0000 - val_loss: 49886552.0000
Epoch 99/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 49078764.0000 - val_loss: 49392224.0000
Epoch 100/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 47750316.0000 - val_loss: 48667524.0000

In [32]:
y_pred = model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

In [33]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"R² Score: {r2:.4f}")

print("\n🔢 Sample Predictions:")
for i in range(10):
    print(f"Person {i+1}: Predicted=${y_pred[i][0]:,.2f} | Actual=${y_test.iloc[i]:,.2f}")

MAE: 5415.19
MSE: 54797098.87
R² Score: 0.7018

🔢 Sample Predictions:
Person 1: Predicted=$8,220.21 | Actual=$8,688.86
Person 2: Predicted=$7,499.83 | Actual=$5,708.87
Person 3: Predicted=$14,837.73 | Actual=$11,436.74
Person 4: Predicted=$27,797.70 | Actual=$38,746.36
Person 5: Predicted=$12,686.93 | Actual=$4,463.21
Person 6: Predicted=$17,125.33 | Actual=$9,304.70
Person 7: Predicted=$21,239.03 | Actual=$38,511.63
Person 8: Predicted=$3,361.05 | Actual=$2,150.47
Person 9: Predicted=$12,601.83 | Actual=$7,345.73
Person 10: Predicted=$14,227.25 | Actual=$10,264.44